apiVersion: v1
kind: Service
metadata:
  name: kube-fswatch
  labels:
    k8s-app: kube-fswatch
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    k8s-app: kube-fswatch
